# Generated by Django 5.2.5 on 2025-11-16 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wrapped_dek_b64', models.TextField(blank=True, default='')),
                ('dek_wrap_nonce_b64', models.CharField(blank=True, default='', max_length=64)),
                ('ciphertext_b64', models.TextField(blank=True, default='')),
                ('item_nonce_b64', models.CharField(blank=True, default='', max_length=64)),
                ('item_salt_b64', models.CharField(blank=True, default='', max_length=64)),
                ('algo_version', models.SmallIntegerField(default=1)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_vaultitem',
                'ordering': ['-created_at'],
            },
        ),
    ]
