# Generated by Django 5.2.5 on 2025-09-29 13:57

import vault.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultitem',
            name='name',
            field=vault.fields.EncryptedField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='password',
            field=vault.fields.EncryptedField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='username',
            field=vault.fields.EncryptedField(max_length=200),
        ),
    ]
