# Generated by Django 5.2.5 on 2025-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_vaultitem_name_alter_vaultitem_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaultitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='vaultitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vaultitem',
            name='password',
        ),
        migrations.RemoveField(
            model_name='vaultitem',
            name='username',
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='algo_version',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='ciphertext_b64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='dek_wrap_nonce_b64',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='item_nonce_b64',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='wrapped_dek_b64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='vaultitem',
            table='vault_vaultitem',
        ),
    ]
