# Generated by Django 5.2.5 on 2025-10-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_alter_vaultitem_options_remove_vaultitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultitem',
            name='ciphertext_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='dek_wrap_nonce_b64',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='item_nonce_b64',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='wrapped_dek_b64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
