# Generated by Django 5.2.5 on 2025-11-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0004_alter_vaultitem_ciphertext_b64_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaultitem",
            name="dek_rotation_required",
            field=models.BooleanField(default=False),
        ),
    ]
