# Generated by Django 5.2.5 on 2025-10-01 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeystore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amk_key_version', models.SmallIntegerField(default=1)),
                ('wrapped_umk_b64', models.TextField(blank=True, null=True)),
                ('umk_nonce_b64', models.CharField(blank=True, max_length=64, null=True)),
                ('algo_version', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keystore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_userkeystore',
            },
        ),
    ]
