# Generated by Django 5.2.5 on 2025-10-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userkeystore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeystore',
            name='umk_nonce_b64',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userkeystore',
            name='wrapped_umk_b64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
