# Generated by Django 5.2.5 on 2025-11-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userkeystore_umk_nonce_b64_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userkeystore",
            name="kms_encryption_algorithm",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="userkeystore",
            name="kms_key_id",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="userkeystore",
            name="previous_kms_encryption_algorithm",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="userkeystore",
            name="previous_kms_key_id",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="userkeystore",
            name="previous_umk_encryption_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userkeystore",
            name="previous_wrapped_umk_b64",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userkeystore",
            name="umk_encryption_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
